#!/usr/bin/env python3
"""Build a compact macOS .app bundle for RABET."""

import argparse
import platform
import shutil
import subprocess
import sys
import time
from pathlib import Path

from build_packaging_common import (
    APP_DESCRIPTION,
    APP_NAME,
    APP_VERSION,
    COMMON_BINARY_EXCLUDE_PATTERNS,
    HIDDEN_DEPENDENCIES,
    ROOT_DIR,
    cleanup_pyinstaller_output,
    copy_runtime_assets,
    display_size_summary,
    ensure_required_files,
    get_data_files,
    get_excluded_modules,
    install_build_dependencies,
    prepare_build_dirs,
    run_pyinstaller,
    write_readme,
)


# NOTE (1.3.1): ``find_macos_vlc`` has been removed alongside the
# python-vlc backend. PyAV's macOS wheel bundles FFmpeg inside the
# package, so the build no longer needs to locate a system
# ``VLC.app``.


def create_spec(args):
    """Generate a PyInstaller spec for a macOS app bundle."""
    excluded_modules = get_excluded_modules(args.exclude_module, args.include_module)
    binary_excludes = list(dict.fromkeys(COMMON_BINARY_EXCLUDE_PATTERNS + args.exclude_binary))
    datas = get_data_files(include_ico=False, include_icns=True, include_png=True)
    icon_path = ROOT_DIR / "resources" / "RABET.icns"
    spec_path = ROOT_DIR / "RABET_macos.spec"

    spec_content = f"""
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_macos_optimized.py

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

excluded_modules = {repr(excluded_modules)}
excluded_binaries = {repr(binary_excludes)}
hiddenimports = {repr(HIDDEN_DEPENDENCIES)}
datas = {repr(datas)}

# 1.3.2: krippendorff and filetype are imported lazily inside RABET
# helpers and PyInstaller's static analyser misses them. Force-collect
# their submodules and data files.
for _lazy_pkg in ('krippendorff', 'filetype', 'pingouin', 'scipy'):
    try:
        hiddenimports += collect_submodules(_lazy_pkg)
        datas += collect_data_files(_lazy_pkg)
    except Exception as _exc:
        print(f'Warning: could not collect {{_lazy_pkg}}: {{_exc}}')


def _keep_binary(item):
    text = " ".join(str(part) for part in item)
    return not any(pattern in text for pattern in excluded_binaries)


a = Analysis(
    ['main.py'],
    pathex=[{repr(str(ROOT_DIR))}],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{'matplotlib': {{'backends': ['QtAgg', 'svg', 'pdf']}}}},
    runtime_hooks=[],
    excludes=excluded_modules,
    # 1.3.3 fix: see comment in build_windows_optimized.py — same
    # zlib PYZ decompression bug applies cross-platform.
    noarchive=True,
)

a.binaries = TOC([item for item in a.binaries if _keep_binary(item)])

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name={repr(APP_NAME)},
    debug=False,
    bootloader_ignore_signals=False,
    strip={not args.no_strip},
    upx=False,
    console={args.console},
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch={repr(args.target_arch)},
    codesign_identity={repr(args.sign_identity) if args.sign_identity else None},
    entitlements_file={repr(args.entitlements) if args.entitlements else None},
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip={not args.no_strip},
    upx=False,
    upx_exclude=[],
    name={repr(APP_NAME)},
)

app = BUNDLE(
    coll,
    name={repr(APP_NAME + '.app')},
    icon={repr(str(icon_path)) if icon_path.exists() else None},
    bundle_identifier='org.rabet.app',
    info_plist={{
        'CFBundleName': {repr(APP_NAME)},
        'CFBundleDisplayName': {repr(APP_NAME)},
        'CFBundleShortVersionString': {repr(APP_VERSION)},
        'CFBundleVersion': {repr(APP_VERSION)},
        'NSHumanReadableCopyright': 'Copyright 2026 Koshiro Mitsui. Released under the MIT License.',
        'NSHighResolutionCapable': 'True',
        'NSPrincipalClass': 'NSApplication',
    }},
)
"""
    spec_path.write_text(spec_content.lstrip(), encoding="utf-8")
    return spec_path


def create_macos_zip(app_path, dist_dir):
    """Create a Finder-friendly zip containing the .app bundle and README."""
    dist_dir = Path(dist_dir)
    app_path = Path(app_path)
    package_dir = dist_dir / f"{APP_NAME}-macOS"
    zip_path = dist_dir / f"{APP_NAME}-macOS.zip"

    if package_dir.exists():
        shutil.rmtree(package_dir)
    package_dir.mkdir()

    readme_path = dist_dir / "README.txt"
    if readme_path.exists():
        shutil.copy2(readme_path, package_dir / "README.txt")

    packaged_app_path = package_dir / app_path.name
    ditto = shutil.which("ditto")
    if ditto:
        subprocess.check_call([ditto, str(app_path), str(packaged_app_path)])
    else:
        shutil.copytree(app_path, packaged_app_path, symlinks=True)

    if zip_path.exists():
        zip_path.unlink()

    if ditto:
        subprocess.check_call(
            [
                ditto,
                "-c",
                "-k",
                "--sequesterRsrc",
                "--keepParent",
                str(package_dir),
                str(zip_path),
            ]
        )
    else:
        archive_base = zip_path.with_suffix("")
        shutil.make_archive(str(archive_base), "zip", root_dir=dist_dir, base_dir=package_dir.name)

    return zip_path


def main():
    parser = argparse.ArgumentParser(description=f"Build {APP_NAME} for macOS")
    parser.add_argument("--skip-deps", action="store_true", help="Do not install missing Python dependencies")
    parser.add_argument("--skip-clean", action="store_true", help="Keep existing build/dist directories")
    parser.add_argument("--skip-cleanup", action="store_true", help="Skip post-build size cleanup")
    parser.add_argument("--spec-only", action="store_true", help="Generate RABET_macos.spec and stop")
    parser.add_argument("--verbose", action="store_true", help="Show verbose PyInstaller output")
    parser.add_argument("--console", action="store_true", help="Show a console window for debug builds")
    parser.add_argument("--no-strip", action="store_true", help="Disable binary stripping")
    parser.add_argument("--no-zip", action="store_true", help="Do not create a zip archive")
    parser.add_argument(
        "--target-arch",
        choices=["arm64", "x86_64", "universal2"],
        default=None,
        help="Optional macOS architecture target. universal2 needs a universal Python environment.",
    )
    parser.add_argument("--sign-identity", default=None, help="Optional codesign identity")
    parser.add_argument("--entitlements", default=None, help="Optional entitlements plist path")
    parser.add_argument("--exclude-module", action="append", default=[], help="Extra module to exclude")
    parser.add_argument("--include-module", action="append", default=[], help="Excluded module to keep")
    parser.add_argument("--exclude-binary", action="append", default=[], help="Extra binary name pattern to exclude")
    args = parser.parse_args()

    if platform.system() != "Darwin":
        print("Error: this script must be run on macOS to create a .app bundle.")
        sys.exit(1)

    print(f"===== Building {APP_NAME} for macOS =====")
    print(APP_DESCRIPTION)
    start_time = time.time()

    if not args.skip_deps:
        install_build_dependencies()
    else:
        print("Skipping dependency installation.")

    ensure_required_files()

    # 1.3.1: no system VLC check; PyAV ships FFmpeg inside its wheel.

    _build_dir, dist_dir = prepare_build_dirs(skip_clean=args.skip_clean)
    spec_path = create_spec(args)
    print(f"Spec file written: {spec_path}")

    if args.spec_only:
        print("Spec-only mode complete.")
        return

    run_pyinstaller(spec_path, verbose=args.verbose)

    app_path = dist_dir / f"{APP_NAME}.app"
    if not app_path.exists():
        raise FileNotFoundError(f"Expected app bundle was not created: {app_path}")

    resources_dir = app_path / "Contents" / "Resources"
    copy_runtime_assets(resources_dir, include_ico=False, include_icns=True, include_png=True)
    write_readme(dist_dir, "macOS")

    if not args.skip_cleanup:
        cleanup_pyinstaller_output(app_path, "macos", verbose=args.verbose)

    zip_path = None
    if not args.no_zip:
        zip_path = create_macos_zip(app_path, dist_dir)
        print(f"Zip archive created: {zip_path}")

    display_size_summary(app_path, extra_paths=[zip_path] if zip_path else None)

    elapsed = time.time() - start_time
    print(f"\nBuild completed in {elapsed:.2f} seconds ({elapsed / 60:.2f} minutes)")
    print(f"Application bundle: {app_path}")
    print("Note: unsigned apps may require right-click > Open on first launch.")


if __name__ == "__main__":
    main()
