#!/usr/bin/env python3
"""Build a compact Linux distribution folder for RABET."""

import argparse
import platform
import shutil
import sys
import time
from pathlib import Path

from build_packaging_common import (
    APP_DESCRIPTION,
    APP_NAME,
    COMMON_BINARY_EXCLUDE_PATTERNS,
    HIDDEN_DEPENDENCIES,
    ROOT_DIR,
    cleanup_pyinstaller_output,
    copy_runtime_assets,
    create_tar_gz,
    display_size_summary,
    ensure_required_files,
    get_data_files,
    get_excluded_modules,
    install_build_dependencies,
    prepare_build_dirs,
    run_pyinstaller,
    write_readme,
)


# NOTE (1.3.1): ``find_linux_vlc`` has been removed alongside the
# python-vlc backend. PyAV's manylinux wheel bundles the FFmpeg
# shared objects (``libav*.so``), so the build no longer scans
# ``/usr/lib*`` for ``libvlc.so``.


def create_spec(args):
    """Generate a PyInstaller spec for Linux."""
    excluded_modules = get_excluded_modules(args.exclude_module, args.include_module)
    binary_excludes = list(dict.fromkeys(COMMON_BINARY_EXCLUDE_PATTERNS + args.exclude_binary))
    datas = get_data_files(include_icns=False)
    spec_path = ROOT_DIR / "RABET_linux.spec"
    strip_binaries = not args.no_strip

    common_header = f"""
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_linux_optimized.py

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

excluded_modules = {repr(excluded_modules)}
excluded_binaries = {repr(binary_excludes)}
hiddenimports = {repr(HIDDEN_DEPENDENCIES)}
datas = {repr(datas)}

# 1.3.2: krippendorff and filetype are imported lazily inside RABET
# helpers and PyInstaller's static analyser misses them. Force-collect
# their submodules and data files.
for _lazy_pkg in ('krippendorff', 'filetype', 'pingouin', 'scipy'):
    try:
        hiddenimports += collect_submodules(_lazy_pkg)
        datas += collect_data_files(_lazy_pkg)
    except Exception as _exc:
        print(f'Warning: could not collect {{_lazy_pkg}}: {{_exc}}')


def _keep_binary(item):
    text = " ".join(str(part) for part in item)
    return not any(pattern in text for pattern in excluded_binaries)


a = Analysis(
    ['main.py'],
    pathex=[{repr(str(ROOT_DIR))}],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{'matplotlib': {{'backends': ['QtAgg']}}}},
    runtime_hooks=[],
    excludes=excluded_modules,
    noarchive=False,
)

a.binaries = TOC([item for item in a.binaries if _keep_binary(item)])

pyz = PYZ(a.pure)
"""

    if args.onefile:
        body = f"""
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name={repr(APP_NAME)},
    debug=False,
    bootloader_ignore_signals=False,
    strip={strip_binaries},
    upx={args.upx},
    console={args.console},
    disable_windowed_traceback=False,
)
"""
    else:
        body = f"""
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name={repr(APP_NAME)},
    debug=False,
    bootloader_ignore_signals=False,
    strip={strip_binaries},
    upx={args.upx},
    console={args.console},
    disable_windowed_traceback=False,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip={strip_binaries},
    upx={args.upx},
    upx_exclude=[],
    name={repr(APP_NAME + '-linux')},
)
"""

    spec_path.write_text((common_header + body).lstrip(), encoding="utf-8")
    return spec_path


def create_linux_launchers(target_dir):
    """Create small Linux launcher and desktop entry files."""
    target_dir = Path(target_dir)

    launcher = target_dir / "run_rabet.sh"
    launcher.write_text(
        """#!/usr/bin/env bash
set -e
APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec "$APP_DIR/RABET" "$@"
""",
        encoding="utf-8",
    )
    launcher.chmod(0o755)

    desktop_file = target_dir / "RABET.desktop"
    desktop_file.write_text(
        f"""[Desktop Entry]
Type=Application
Name={APP_NAME}
Comment={APP_DESCRIPTION}
Exec=RABET
Icon=resources/RABET.png
Terminal=false
Categories=Science;Education;
""",
        encoding="utf-8",
    )

    installer = target_dir / "install_desktop_entry.sh"
    installer.write_text(
        f"""#!/usr/bin/env bash
set -e
APP_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
DESKTOP_DIR="${{HOME}}/.local/share/applications"
ICON_DIR="${{HOME}}/.local/share/icons/hicolor/256x256/apps"
mkdir -p "$DESKTOP_DIR" "$ICON_DIR"
cp "$APP_DIR/resources/RABET.png" "$ICON_DIR/{APP_NAME}.png"
cat > "$DESKTOP_DIR/{APP_NAME}.desktop" <<EOF
[Desktop Entry]
Type=Application
Name={APP_NAME}
Comment={APP_DESCRIPTION}
Exec=$APP_DIR/{APP_NAME}
Icon={APP_NAME}
Terminal=false
Categories=Science;Education;
EOF
chmod +x "$DESKTOP_DIR/{APP_NAME}.desktop"
echo "Installed desktop launcher: $DESKTOP_DIR/{APP_NAME}.desktop"
""",
        encoding="utf-8",
    )
    installer.chmod(0o755)


def main():
    parser = argparse.ArgumentParser(description=f"Build {APP_NAME} for Linux")
    parser.add_argument("--skip-deps", action="store_true", help="Do not install missing Python dependencies")
    parser.add_argument("--skip-clean", action="store_true", help="Keep existing build/dist directories")
    parser.add_argument("--skip-cleanup", action="store_true", help="Skip post-build size cleanup")
    parser.add_argument("--spec-only", action="store_true", help="Generate RABET_linux.spec and stop")
    parser.add_argument("--verbose", action="store_true", help="Show verbose PyInstaller output")
    parser.add_argument("--console", action="store_true", help="Show terminal output in the built app")
    parser.add_argument("--no-strip", action="store_true", help="Disable binary stripping")
    parser.add_argument("--onefile", action="store_true", help="Build a single executable instead of an app folder")
    parser.add_argument("--no-archive", action="store_true", help="Do not create a tar.gz archive")
    parser.add_argument("--upx", action="store_true", help="Use UPX if installed. Test carefully with Qt apps.")
    parser.add_argument("--exclude-module", action="append", default=[], help="Extra module to exclude")
    parser.add_argument("--include-module", action="append", default=[], help="Excluded module to keep")
    parser.add_argument("--exclude-binary", action="append", default=[], help="Extra binary name pattern to exclude")
    args = parser.parse_args()

    if platform.system() != "Linux":
        print("Error: this script must be run on Linux to create a Linux build.")
        sys.exit(1)

    print(f"===== Building {APP_NAME} for Linux =====")
    print(APP_DESCRIPTION)
    start_time = time.time()

    if args.upx and not shutil.which("upx"):
        print("Warning: UPX was requested but not found. Continuing without UPX.")
        args.upx = False

    if not args.skip_deps:
        install_build_dependencies()
    else:
        print("Skipping dependency installation.")

    ensure_required_files()

    # 1.3.1: PyAV bundles FFmpeg inside its wheel, so the previous
    # ``find_linux_vlc`` runtime check is gone.

    _build_dir, dist_dir = prepare_build_dirs(skip_clean=args.skip_clean)
    spec_path = create_spec(args)
    print(f"Spec file written: {spec_path}")

    if args.spec_only:
        print("Spec-only mode complete.")
        return

    run_pyinstaller(spec_path, verbose=args.verbose)

    if args.onefile:
        target_path = dist_dir / APP_NAME
        if not target_path.exists():
            raise FileNotFoundError(f"Expected executable was not created: {target_path}")
        target_dir = dist_dir / f"{APP_NAME}-linux"
        target_dir.mkdir(exist_ok=True)
        shutil.move(str(target_path), target_dir / APP_NAME)
    else:
        target_dir = dist_dir / f"{APP_NAME}-linux"
        if not target_dir.exists():
            raise FileNotFoundError(f"Expected app folder was not created: {target_dir}")

    copy_runtime_assets(target_dir)
    write_readme(target_dir, "Linux")
    create_linux_launchers(target_dir)

    if not args.skip_cleanup:
        cleanup_pyinstaller_output(target_dir, "linux", verbose=args.verbose)

    archive_path = None
    if not args.no_archive:
        arch = platform.machine() or "unknown"
        archive_path = create_tar_gz(target_dir, dist_dir / f"{APP_NAME}-linux-{arch}.tar.gz")
        print(f"Archive created: {archive_path}")

    display_size_summary(target_dir, extra_paths=[archive_path] if archive_path else None)

    elapsed = time.time() - start_time
    print(f"\nBuild completed in {elapsed:.2f} seconds ({elapsed / 60:.2f} minutes)")
    print(f"Application folder: {target_dir}")


if __name__ == "__main__":
    main()
