name: Build macOS Distribution

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PySide6 python-vlc numpy pandas matplotlib Pillow
        pip install setuptools jaraco.text jaraco.classes jaraco.collections
        pip install importlib_metadata importlib_resources more_itertools packaging
    
    - name: Build with PyInstaller
      run: |
        # Create a Mac-specific build script
        cat > build_mac.py << 'EOF'
        import os
        import sys
        import subprocess
        
        # Run PyInstaller with Mac-specific options
        cmd = [
            sys.executable, "-m", "PyInstaller",
            "--onefile",
            "--windowed",  # No console window on Mac
            "--icon=resources/RABET.icns",  # Mac icon format
            "--name=RABET",
            "--add-data=resources:resources",
            "--add-data=configs:configs",
            "--hidden-import=matplotlib.backends.backend_qt5agg",
            "--hidden-import=PIL",
            "--hidden-import=PIL.Image",
            "--exclude-module=tkinter",
            "main.py"
        ]
        
        subprocess.check_call(cmd)
        EOF
        
        python build_mac.py
    
    - name: Create DMG installer
      run: |
        # Install create-dmg
        brew install create-dmg
        
        # Create a DMG
        create-dmg \
          --volname "RABET" \
          --window-pos 200 120 \
          --window-size 600 400 \
          --icon-size 100 \
          --icon "RABET.app" 200 190 \
          --hide-extension "RABET.app" \
          --app-drop-link 400 190 \
          "RABET-macOS.dmg" \
          "dist/"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: RABET-macOS
        path: |
          dist/RABET
          RABET-macOS.dmg
